name: CI - Analyse des Logs
on:
  push:
    branches: [main, dev]  # Déclencheur sur main ET dev
  pull_request:
    branches: [main]

jobs:
  analyse-logs:
    runs-on: ubuntu-latest
    
    steps:
    # Étape 1: Récupération du code
    - uses: actions/checkout@v4
    
    # Étape 2: Configuration de Node.js
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    # Étape 3: Installation des dépendances
    - name: Installer les dépendances
      run: npm install chalk
      working-directory: ./log-analyzer  # Important : cible le bon dossier
    
    # Étape 4: Exécution du script avec vérification
    - name: Exécuter et tester l'analyseur
      working-directory: ./log-analyzer  # Exécution dans le sous-dossier
      run: |
        # Génère un fichier log.txt de test
        echo "INFO Test 1" > log.txt
        echo "ERROR Test 2" >> log.txt
        echo "WARNING Test 3" >> log.txt
        
        # Capture la sortie du script
        OUTPUT=$(node analyse-logs.js)
        echo "$OUTPUT"
        
        # Vérifications automatiques
        if [[ $(grep -c 'ERROR' log.txt) -ne 1 ]]; then
          echo "ERREUR: Nombre d'ERROR incorrect"
          exit 1
        fi
        
        if [[ $(grep -c 'WARNING' log.txt) -ne 1 ]]; then
          echo "ERREUR: Nombre de WARNING incorrect"
          exit 1
        fi

        if [[ $(grep -c 'INFO' log.txt) -ne 1 ]]; then
          echo "ERREUR: Nombre d'INFO incorrect"
          exit 1
        fi
        
        echo "✅ Tous les tests passent !"
